### ISSUE TITLE
Editar Endereço (FINALIZAR PEDIDO)

### ISSUE THREAD

**Issue by EloisaFagundes** [future4code/sagan-4food-A#10]
> Esse componente edita o endereço que o usuário colocou inicialmente no cadastro.

responsável por esse card: @lfvirtuoso 

*Componente Endereço*

Deve conter perfil do usuário com as informações Logradouro, número, complemento, bairro, cidade, estado com opção de um botão para salvar.

*CHECKLIST*

- [ ]  **componente HEADER**

1. - [ ] Deve conter o nome da página
2. - [ ] Deve conter botão para voltar a página anterior "<"

- [ ]  **componente CONTAINER**

1. - [ ] Input  com preenchimento obrigatório _Logradouro_
2. - [ ] Input  com preenchimento obrigatório _Número_
3. - [ ] Input  com preenchimento NÃO obrigatório _Complemento_
4. - [ ] Input  com preenchimento obrigatório _Bairro_
5. - [ ] Input  com preenchimento obrigatório _Cidade_
6. - [ ] Input  com preenchimento obrigatório _Estado_
7. - [ ] BOTÃO salvar

- [ ] **API**

- [ ] **ROTAS**

- [ ] Editar Endereço -> Meu Perfil

**Comment by EduCosta85** [comment]
Criado uma action para cadastro de um endereco obrigatorio, que pode ser reaproveitado
"doNewAddress", é interessante reaproveitar aqui
