### ISSUE TITLE
Componente (APPBAR)

### ISSUE THREAD

**Issue by EloisaFagundes** [future4code/sagan-4food-A#14]
> Contém nome da página que o usuário está acessando. Pode ou não ter uma seta para voltar para a página anterior. 

Responsável por esse card: @EloisaFagundes 

*Checklist*

- [ ] estilizar com Material-UI
- [ ] Adiciona título chumbado
- [ ] muda para variável o título

[
![image](https://user-images.githubusercontent.com/59846340/79154418-e13a6d80-7da5-11ea-9971-bc45225e2b44.png)
](url)

**Comment by EduCosta85** [comment]
@EloisaFagundes criei um componente "HistoryDivider" que acho que ta fazendo isso (não entendi bem o enunciado...) da uma olhada por favor? (ta no PR aberto) tks!
